import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg(process.env.DATABASE_URL!);
const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

const RECIPES = [
  {
    externalId: 'seed-spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    price: 18.50,
    category: 'pasta',
    tags: ['italian', 'beef', 'comfort-food'],
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 4,
    cuisine: 'Italian',
    cookTimeMinutes: 45,
    calories: 620,
    description: 'Classic Italian meat sauce slow-cooked with tomatoes, herbs, and ground beef over al dente spaghetti.',
  },
  {
    externalId: 'seed-margherita-pizza',
    name: 'Margherita Pizza',
    price: 14.00,
    category: 'pizza',
    tags: ['italian', 'vegetarian', 'cheese'],
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'Italian',
    cookTimeMinutes: 25,
    calories: 520,
    description: 'Wood-fired style pizza with San Marzano tomatoes, fresh mozzarella, and basil.',
  },
  {
    externalId: 'seed-pan-seared-salmon',
    name: 'Pan-Seared Salmon',
    price: 26.00,
    category: 'seafood',
    tags: ['fish', 'healthy', 'omega-3', 'gluten-free'],
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'American',
    cookTimeMinutes: 20,
    calories: 380,
    description: 'Perfectly seared Atlantic salmon fillet with crispy skin, lemon butter, and fresh herbs.',
  },
  {
    externalId: 'seed-caesar-salad',
    name: 'Caesar Salad',
    price: 11.00,
    category: 'salad',
    tags: ['vegetarian', 'light', 'lunch'],
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'American',
    cookTimeMinutes: 10,
    calories: 280,
    description: 'Crisp romaine lettuce, housemade Caesar dressing, shaved parmesan, and crunchy croutons.',
  },
  {
    externalId: 'seed-chicken-noodle-soup',
    name: 'Chicken Noodle Soup',
    price: 13.50,
    category: 'soup',
    tags: ['chicken', 'comfort-food', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 4,
    cuisine: 'American',
    cookTimeMinutes: 40,
    calories: 320,
    description: 'Hearty chicken broth with tender vegetables, shredded chicken, and egg noodles.',
  },
  {
    externalId: 'seed-street-tacos',
    name: 'Street Tacos',
    price: 16.00,
    category: 'mexican',
    tags: ['beef', 'spicy', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 3,
    cuisine: 'Mexican',
    cookTimeMinutes: 20,
    calories: 420,
    description: 'Authentic carne asada street tacos with fresh salsa, cilantro, and lime on corn tortillas.',
  },
  {
    externalId: 'seed-salmon-sushi-rolls',
    name: 'Salmon Sushi Rolls',
    price: 22.00,
    category: 'japanese',
    tags: ['sushi', 'fish', 'rice', 'gluten-free'],
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'Japanese',
    cookTimeMinutes: 30,
    calories: 340,
    description: 'Fresh salmon maki rolls with sushi rice, nori, and avocado. Served with soy and wasabi.',
  },
  {
    externalId: 'seed-ribeye-steak',
    name: 'Ribeye Steak',
    price: 38.00,
    category: 'beef',
    tags: ['steak', 'dinner', 'keto', 'gluten-free'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'American',
    cookTimeMinutes: 25,
    calories: 680,
    description: '12oz prime ribeye cooked to order with garlic herb butter and caramelized mushrooms.',
  },
  {
    externalId: 'seed-vegetable-stir-fry',
    name: 'Vegetable Stir Fry',
    price: 12.00,
    category: 'asian',
    tags: ['vegan', 'vegetables', 'quick', 'healthy'],
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 3,
    cuisine: 'Chinese',
    cookTimeMinutes: 15,
    calories: 260,
    description: 'Seasonal vegetables wok-tossed in savory ginger soy sauce with sesame oil and scallions.',
  },
  {
    externalId: 'seed-grilled-chicken-breast',
    name: 'Grilled Chicken Breast',
    price: 17.00,
    category: 'chicken',
    tags: ['high-protein', 'gluten-free', 'healthy', 'keto'],
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'American',
    cookTimeMinutes: 25,
    calories: 340,
    description: 'Juicy flame-grilled chicken breast marinated in herbs and olive oil. Lean and protein-packed.',
  },
  {
    externalId: 'seed-classic-cheeseburger',
    name: 'Classic Cheeseburger',
    price: 15.50,
    category: 'american',
    tags: ['beef', 'comfort-food', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'American',
    cookTimeMinutes: 20,
    calories: 580,
    description: 'Double smash burger with American cheese, pickles, caramelized onions, and special sauce.',
  },
  {
    externalId: 'seed-bbq-pork-ribs',
    name: 'BBQ Pork Ribs',
    price: 32.00,
    category: 'bbq',
    tags: ['pork', 'smoky', 'weekend', 'gluten-free'],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76538dc82e9?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 4,
    cuisine: 'American',
    cookTimeMinutes: 180,
    calories: 620,
    description: 'Fall-off-the-bone St. Louis ribs slow-smoked with hickory and glazed with house BBQ sauce.',
  },
  {
    externalId: 'seed-poke-bowl',
    name: 'Poke Bowl',
    price: 19.00,
    category: 'hawaiian',
    tags: ['fish', 'rice', 'healthy', 'fresh'],
    imageUrl: 'https://images.unsplash.com/photo-1584776851497-51438b804e6f?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 1,
    cuisine: 'Hawaiian',
    cookTimeMinutes: 15,
    calories: 420,
    description: 'Fresh ahi tuna over sushi rice with edamame, cucumber, avocado, and ponzu drizzle.',
  },
  {
    externalId: 'seed-tonkotsu-ramen',
    name: 'Tonkotsu Ramen',
    price: 21.00,
    category: 'japanese',
    tags: ['noodles', 'pork', 'broth', 'comfort-food'],
    imageUrl: 'https://images.unsplash.com/photo-1571167530149-c1105da4c285?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'Japanese',
    cookTimeMinutes: 60,
    calories: 540,
    description: 'Rich pork bone broth with ramen noodles, soft-boiled egg, chashu, nori, and scallions.',
  },
  {
    externalId: 'seed-pasta-carbonara',
    name: 'Pasta Carbonara',
    price: 17.50,
    category: 'pasta',
    tags: ['italian', 'eggs', 'bacon', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'Italian',
    cookTimeMinutes: 20,
    calories: 560,
    description: 'Authentic Roman pasta with guanciale, egg yolks, Pecorino Romano, and black pepper. No cream.',
  },
  {
    externalId: 'seed-avocado-toast',
    name: 'Avocado Toast',
    price: 9.00,
    category: 'breakfast',
    tags: ['vegan', 'healthy', 'quick', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414f2005?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 1,
    cuisine: 'American',
    cookTimeMinutes: 10,
    calories: 290,
    description: 'Smashed avocado on sourdough with everything bagel seasoning, chili flakes, and lemon.',
  },
  {
    externalId: 'seed-greek-salad',
    name: 'Greek Salad',
    price: 12.50,
    category: 'salad',
    tags: ['mediterranean', 'vegetarian', 'feta', 'healthy'],
    imageUrl: 'https://images.unsplash.com/photo-1515516969354-50de00cda48c?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'Greek',
    cookTimeMinutes: 10,
    calories: 260,
    description: 'Crisp cucumber, tomatoes, Kalamata olives, and creamy feta dressed in extra-virgin olive oil.',
  },
  {
    externalId: 'seed-beef-vegetable-stew',
    name: 'Beef & Vegetable Stew',
    price: 22.00,
    category: 'soup',
    tags: ['beef', 'comfort-food', 'winter', 'slow-cook'],
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 6,
    cuisine: 'American',
    cookTimeMinutes: 120,
    calories: 460,
    description: 'Slow-braised chuck roast with root vegetables in a rich red wine and herb broth.',
  },
  {
    externalId: 'seed-shrimp-pad-thai',
    name: 'Shrimp Pad Thai',
    price: 20.00,
    category: 'asian',
    tags: ['shrimp', 'noodles', 'thai', 'spicy'],
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 2,
    cuisine: 'Thai',
    cookTimeMinutes: 25,
    calories: 480,
    description: 'Classic Thai stir-fried rice noodles with plump shrimp, bean sprouts, egg, and peanuts.',
  },
  {
    externalId: 'seed-mushroom-risotto',
    name: 'Mushroom Risotto',
    price: 18.00,
    category: 'italian',
    tags: ['vegetarian', 'mushroom', 'rice', 'comfort-food'],
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&w=400&h=300&fit=crop&q=80',
    servings: 3,
    cuisine: 'Italian',
    cookTimeMinutes: 35,
    calories: 420,
    description: 'Creamy Arborio rice slowly cooked with wild mushrooms, shallots, white wine, and parmesan.',
  },
];

async function main() {
  console.log('[seed] Seeding recipes...');

  for (const recipe of RECIPES) {
    await prisma.recipe.upsert({
      where: { externalId: recipe.externalId },
      create: recipe,
      update: {
        name: recipe.name,
        price: recipe.price,
        imageUrl: recipe.imageUrl,
        tags: recipe.tags,
        cuisine: recipe.cuisine,
        cookTimeMinutes: recipe.cookTimeMinutes,
        calories: recipe.calories,
        description: recipe.description,
      },
    });
  }

  console.log(`[seed] Upserted ${RECIPES.length} recipes.`);
}

main()
  .catch((e) => { console.error('[seed] Error:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
